# Olympic Worlds
---

Olympians

Team members:
- Salman Bader Al-Haddad
- Sayed Hussain Asaad Almukhtar

## Introduction 
__Introduction to the topic__ 

    ...

---

## Problem Statement

    ...

## Objectives:
__Questions that will guide the analysis to solve the problem__

    ...

---

## Exploratory Data Analysis (EDA):

### Data Info:
__Getting the data and exploring it (includes descriptive statistics)__

#### Sayed Hussain

In [1]:
# import data manupilation modules
import pandas as pd
import numpy as np
import csv

# import libraries for visualization
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Now we will define the data path
olympic_events_path = 'Data//athlete_events.csv'
olympic_regions_path = 'Data//noc_regions.csv'

#Loading The Files
olympic_events_df = pd.read_csv(olympic_events_path)
olympic_regions_df = pd.read_csv(olympic_regions_path)

display(olympic_events_df.head())
display(olympic_regions_df.head())

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,City,Sport,Event,Medal
0,1,A Dijiang,male,24.0,180.0cm,80.0kg,China,CHN,1992 Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,Male,23.0,170.0cm,60.0kg,China,CHN,2012 Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,Male,24.0,NaN,NaN,Denmark,DEN,1920 Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,FeMale,21.0,185.0cm,82.0kg,Netherlands,NED,1988 Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [3]:
#Let us now check the data types

print("orders_df dtypes:\n", olympic_events_df.dtypes, "\n")
print("customers_df dtypes:\n", olympic_regions_df.dtypes, "\n")

orders_df dtypes:
 ID          int64
Name       object
Sex        object
Age       float64
Height     object
Weight     object
Team       object
NOC        object
Games      object
City       object
Sport      object
Event      object
Medal      object
dtype: object

customers_df dtypes:
 NOC       object
region    object
notes     object
dtype: object

In [4]:
#Now we want to transform the height into a number so we removed the String
olympic_events_df['Height'] = olympic_events_df['Height'].str.replace('cm', '')

In [5]:
#We can Check here
olympic_events_df['Height']

0         180.0
1         170.0
2           NaN
3           NaN
4         185.0
          ...
271111    179.0
271112    176.0
271113    176.0
271114    185.0
271115    185.0
Name: Height, Length: 271116, dtype: object

In [6]:
#Now we do the same for weight
olympic_events_df['Weight'] = olympic_events_df['Weight'].str.replace('kg', '')
olympic_events_df['Height']

0         180.0
1         170.0
2           NaN
3           NaN
4         185.0
          ...
271111    179.0
271112    176.0
271113    176.0
271114    185.0
271115    185.0
Name: Height, Length: 271116, dtype: object

# Salman

In [7]:
# discover the unique variables in the sex attribute
print(olympic_events_df["Sex"].unique())
print(len(olympic_events_df["Sex"].unique()))

['male' 'Male' 'M' 'FeMale' 'F' 'Female']
6

In [8]:
# Unifying names in one form in sex attribute
olympic_events_df["Sex"] = olympic_events_df["Sex"].replace({"male":"Male", "M":"Male", "FeMale" : "Female", "F" : "Female"})

In [9]:
olympic_events_df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,City,Sport,Event,Medal
0,1,A Dijiang,Male,24.0,180.0,80.0,China,CHN,1992 Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,Male,23.0,170.0,60.0,China,CHN,2012 Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,Male,24.0,NaN,NaN,Denmark,DEN,1920 Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,Male,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,Female,21.0,185.0,82.0,Netherlands,NED,1988 Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,Male,29.0,179.0,89.0,Poland-1,POL,1976 Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,Male,27.0,176.0,59.0,Poland,POL,2014 Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,Male,27.0,176.0,59.0,Poland,POL,2014 Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,Male,30.0,185.0,96.0,Poland,POL,1998 Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,Male,34.0,185.0,96.0,Poland,POL,2002 Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [15]:
print(olympic_events_df["Team"].unique())
print(len(olympic_events_df["Team"].unique()))

['China' 'Denmark' 'Denmark/Sweden' ... 'Solos Carex' 'Dow Jones' 'Digby']
1184

In [17]:
# to discover unique age
print(olympic_events_df["Age"].unique())
print(len(olympic_events_df["Age"].unique()))

[24. 23. 34. 21. 25. 27. 31. 33. 18. 26. 22. 30. 32. 28. 54. 20. 17. 43.
 47. 29. 41. 45. 49. 53. 57. nan 19. 38. 35. 16. 37. 15. 42. 46. 40. 36.
 14. 39. 48. 52. 44. 55. 50. 71. 63. 51. 58. 13. 60. 75. 65. 56. 64. 68.
 84. 12. 72. 59. 61. 70. 74. 62. 67. 69. 73. 66. 11. 76. 88. 96. 80. 10.
 81. 77. 97.]
75

In [12]:
# to get information about age attribute

print(olympic_events_df["Age"].info())
print(olympic_events_df["Age"].min())
print(olympic_events_df["Age"].max())
print(olympic_events_df["Age"].mean())

<class 'pandas.core.series.Series'>
RangeIndex: 271116 entries, 0 to 271115
Series name: Age
Non-Null Count   Dtype
--------------   -----
261642 non-null  float64
dtypes: float64(1)
memory usage: 2.1 MB
None
10.0
97.0
25.556898357297374

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,City,Sport,Event,Medal
257054,128719,John Quincy Adams Ward,Male,97.0,NaN,NaN,United States,USA,1928 Summer,Amsterdam,Art Competitions,"Art Competitions Mixed Sculpturing, Statues",NaN

In [13]:
# get information about this person (10 years old)
olympic_events_df[olympic_events_df["Age"] == 10]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,City,Sport,Event,Medal
142882,71691,Dimitrios Loundras,Male,10.0,NaN,NaN,Ethnikos Gymnastikos Syllogos,GRE,1896 Summer,Athina,Gymnastics,"Gymnastics Men's Parallel Bars, Teams",Bronze

In [14]:
# # get information about this person (97 years old)
olympic_events_df[olympic_events_df["Age"] == 97]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,City,Sport,Event,Medal
257054,128719,John Quincy Adams Ward,Male,97.0,NaN,NaN,United States,USA,1928 Summer,Amsterdam,Art Competitions,"Art Competitions Mixed Sculpturing, Statues",NaN

In [10]:
# get information about nan values
nan_counts = olympic_events_df.isna().sum()
print(nan_counts)

ID             0
Name           0
Sex            0
Age         9474
Height     60171
Weight     62875
Team           0
NOC            0
Games          0
City           0
Sport          0
Event          0
Medal     231333
dtype: int64

In [15]:
# to find the percentage of nan values in each attribute
olympic_events_df.isna().mean() * 100

ID         0.000000
Name       0.000000
Sex        0.000000
Age        3.494445
Height    22.193821
Weight    23.191180
Team       0.000000
NOC        0.000000
Games      0.000000
City       0.000000
Sport      0.000000
Event      0.000000
Medal     85.326207
dtype: float64

In [21]:
# Convert Height to numeric rather than object
olympic_events_df["Height"] = pd.to_numeric(olympic_events_df["Height"])

In [26]:
# Convert Weight to numeric rather than object (use a different way)
olympic_events_df["Weight"] = olympic_events_df["Weight"].astype("float64")

In [23]:
olympic_events_df['Height'] = (
    olympic_events_df.groupby(['Sex', 'Sport', 'NOC'])['Height']
    .transform(lambda x: x.fillna(x.median()))
)

In [24]:
olympic_events_df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,City,Sport,Event,Medal
0,1,A Dijiang,Male,24.0,180.0,80.0,China,CHN,1992 Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,Male,23.0,170.0,60.0,China,CHN,2012 Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,Male,24.0,183.0,NaN,Denmark,DEN,1920 Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,Male,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,Female,21.0,185.0,82.0,Netherlands,NED,1988 Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,Male,29.0,179.0,89.0,Poland-1,POL,1976 Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,Male,27.0,176.0,59.0,Poland,POL,2014 Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,Male,27.0,176.0,59.0,Poland,POL,2014 Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,Male,30.0,185.0,96.0,Poland,POL,1998 Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,Male,34.0,185.0,96.0,Poland,POL,2002 Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [25]:
olympic_events_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 13 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  267453 non-null  float64
 5   Weight  208241 non-null  object
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   City    271116 non-null  object
 10  Sport   271116 non-null  object
 11  Event   271116 non-null  object
 12  Medal   39783 non-null   object
dtypes: float64(2), int64(1), object(10)
memory usage: 26.9+ MB

#### Sayed Hussain

#### Salman

### Analysis: 
__Answering the objectives through data analysis__

#### Sayed Hussain

#### Salman

---

## Summary
__Summarizing the key insights from the analysis__

**Note**: _Use Bullet Points_

    ...

## Recommendations/Conclusion
**Note**: _Use Bullet Points_

    ...